name: Build Typst Docs

on: [push]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Compile Typst Files
      uses: ammar-ahmed22/compile-typst-action@v1
      with:
        source_paths: 'hw/hw3-extra/main.typ'
        output_paths: 'honor-paper.pdf'
